inputs:
  system:
    description: 'Target operating system'
    required: true
    default: 'archlinux'
  arch:
    description: 'Target architecture'
    required: true
    default: 'x86_64'

runs:
  using: 'composite'
  steps:
    - name: Upload version artifact
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: xava-x86_64.AppImage
        path: build/xava-x86_64.AppImage

    - name: Upload version artifact
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: version.txt
        path: build/version.txt

