name: Build

on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
        - system: archlinux
          arch: x86_64
          icon: '🟦'
        - system: windows
          arch: i686
          icon: '⬛'
        - system: windows
          arch: x86_64
          icon: '🟦'

    name: 🚧${{ matrix.icon }} ${{ matrix.system }} (${{ matrix.arch }})
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: ./.github/actions/prepare
      with:
        system: ${{ matrix.system }}
        arch:   ${{ matrix.arch   }}

    - uses: ./.github/actions/compile
      with:
        system: ${{ matrix.system }}
        arch:   ${{ matrix.arch   }}

    - uses: ./.github/actions/upload
      if: ${{ !env.ACT }}
      with:
        system: ${{ matrix.system }}
        arch:   ${{ matrix.arch   }}

  create-release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: rm -rf *
      - uses: actions/download-artifact@v3

      - name: Reorganize release files
        run: |
          ls -R
          for i in xava-*; do
            mv $i temp
            mv temp/$i $i
            rmdir temp
          done
          ls -R

      - name: Read version file
        run: |
          cat version.txt/version.txt
          VER=$(cat version.txt/version.txt)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          repo_token: "${{ secrets.GH_ACCESS_TOKEN }}"
          automatic_release_tag: ${{ env.VERSION }}
          prerelease: true
          title: "Development Build"
          files: |
            xava-installer-i686.exe
            xava-installer-x86_64.exe
            xava-x86_64.AppImage

